language: node_js
node_js:
    - "8"
stages:
  - name: build
  # Build the docker image only on master branch
  - name: deploy

branches:
  only:
  - master

cache: npm

before_install:
  - cd web
  - npm install

jobs:
  include:
    - stage: build
      script:
        - npm run build
    - stage: deploy
      script:
        - npm run deploy

      # deploy:
      #   provider: pages
      #   skip-cleanup: true
      #   github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      #   keep-history: true
      #   local-dir: web/dist # the local dir is relative to root and ignoring the one set with before_install
      #   on:
      #     tags: true
      #     all_branches: true